import { Product } from "./types";

const api = {
    list: async (): Promise<Product[]> => [
        {
            id: 1,
            title: "Blusa con volados",
            price: 17.956,
            image: require("../assets/clothing/blusaconvolados.jpg"),
            image1: require("../assets/clothing/blusaconvolados1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "M", "L"],
            colors: ["#e03920", "#9e256190", "pink"],
            category: "Blusa",
        },
        {
            id: 2,
            title: "Chaqueta Boton",
            price: 23.557,
            image: require("../assets/clothing/chaquetadoblebotonadura.jpg"),
            image1: require("../assets/clothing/chaquetadoblebotonadura1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["M", "L"],
            colors: ["#008000"],
            category: "Chaqueta",
        },
        {
            id: 3,
            title: "Blusa Floral",
            price: 19.996,
            image: require("../assets/clothing/blusafloral.jpg"),
            image1: require("../assets/clothing/blusafloral1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "M"],
            colors: ["#0e3f96", "pink", "black"],
            category: "Blusa",
        },
        {
            id: 4,
            title: "Buzo Oversized",
            price: 35.215,
            image: require("../assets/clothing/buzooversized.jpg"),
            image1: require("../assets/clothing/buzooversized1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["M", "L"],
            colors: ["#0007", "#0307", "black"],
            category: "Buso",
        },
        {
            id: 5,
            title: "Calza",
            price: 12.189,
            image: require("../assets/clothing/calza.jpg"),
            image1: require("../assets/clothing/calza1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "M", "L"],
            colors: ["#5003", "#addd", "#033"],
            category: "Calza",
        },
        {
            id: 6,
            title: "Calza tipo Pescadora",
            price: 13.557,
            image: require("../assets/clothing/calzatipopescadora.jpg"),
            image1: require("../assets/clothing/calzatipopescadora1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "M"],
            colors: ["black", "#033"],
            category: "Calza",
        },
        {
            id: 7,
            title: "Camisa Lisa",
            price: 23.557,
            image: require("../assets/clothing/camisalisa.jpg"),
            image1: require("../assets/clothing/camisalisa1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "M", "L"],
            colors: ["#add", "#aadd", "#33333397"],
            category: "Camisa",
        },
        {
            id: 8,
            title: "Camisa con Encaje",
            price: 25.023,
            image: require("../assets/clothing/camisatransparenteconencaje.jpg"),
            image1: require("../assets/clothing/camisatransparenteconencaje1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["M", "L"],
            colors: ["pink", "black", "#eee1ee"],
            category: "Camisa",
        },
        {
            id: 9,
            title: "Campera Bomber",
            price: 43.205,
            image: require("../assets/clothing/camperabomber.jpg"),
            image1: require("../assets/clothing/camperabomber1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "M", "L"],
            colors: ["black"],
            category: "Campera",
        },
        {
            id: 10,
            title: "Campera Jean",
            price: 33.899,
            image: require("../assets/clothing/camperajean.jpg"),
            image1: require("../assets/clothing/camperajean1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "M"],
            colors: ["black", "#004700"],
            category: "Campera",
        },
        {
            id: 11,
            title: "Cardigan",
            price: 31.592,
            image: require("../assets/clothing/cardigan1.jpg"),
            image1: require("../assets/clothing/cardigann.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "M", "L"],
            colors: ["pink", "#03393097", "#e03920"],
            category: "Cardigan",
        },
        {
            id: 12,
            title: "Blusa estampada",
            price: 28.999,
            image: require("../assets/clothing/blusaestampada.jpg"),
            image1: require("../assets/clothing/blusaestampada1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis ?",
            size: ["S", "M", "L"],
            colors: ["#91a569", "orange"],
            category: "Saco",
        },
        {
            id: 13,
            title: "Chupin Bengalina",
            price: 20.299,
            image: require("../assets/clothing/chupinbengalina.jpg"),
            image1: require("../assets/clothing/chupinbengalina1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "L"],
            colors: ["#ccce0d40", "black"],
            category: "Chupin",
        },
        {
            id: 14,
            title: "Chupin bolsillo",
            price: 22.152,
            image: require("../assets/clothing/chupinbengalinabolsillo.jpg"),
            image1: require("../assets/clothing/chupinbengalinabolsillo1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "M", "L"],
            colors: ["#0f330095", "black"],
            category: "Chupin",
        },
        {
            id: 15,
            title: "Chupin con lazo",
            price: 23.599,
            image: require("../assets/clothing/chupinbengalinaconlazo.jpg"),
            image1: require("../assets/clothing/chupinbengalinaconlazo1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "L"],
            colors: ["black"],
            category: "Chupin",
        },
        {
            id: 16,
            title: "Jeans",
            price: 28.957,
            image: require("../assets/clothing/jeans.jpg"),
            image1: require("../assets/clothing/jeans1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "M", "L"],
            colors: ["blue", "black"],
            category: "Jeans",
        },
        {
            id: 17,
            title: "Remera Calada",
            price: 15.557,
            image: require("../assets/clothing/remeracalada.jpg"),
            image1: require("../assets/clothing/remeracalada1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "M"],
            colors: ["pink", "#9e256190"],
            category: "Remera",
        },
        {
            id: 18,
            title: "Remera cuello V",
            price: 12.035,
            image: require("../assets/clothing/remeracuellov.jpg"),
            image1: require("../assets/clothing/remeracuellov1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "M", "L"],
            colors: ["black", "#33333395"],
            category: "Remera",
        },
        {
            id: 19,
            title: "Remera Encaje",
            price: 19.251,
            image: require("../assets/clothing/remeraencaje.jpg"),
            image1: require("../assets/clothing/remeraencaje1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "L"],
            colors: ["pink", "black"],
            category: "Remera",
        },
        {
            id: 20,
            title: "Remera con manga",
            price: 15.555,
            image: require("../assets/clothing/remeramangamurcielago.jpg"),
            image1: require("../assets/clothing/remeramangamurcielago1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "L"],
            colors: ["pink", "#9e2561"],
            category: "Remera",
        },
        {
            id: 21,
            title: "Remera Sedoso",
            price: 20.089,
            image: require("../assets/clothing/remerasedoso.jpg"),
            image1: require("../assets/clothing/remerasedoso1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["M", "L"],
            colors: ["#cddd", "#ccc"],
            category: "Remera",
        },
        {
            id: 22,
            title: "Sweater con Puntilla",
            price: 44.599,
            image: require("../assets/clothing/sweaterconpuntilla.jpg"),
            image1: require("../assets/clothing/sweaterconpuntilla1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "L"],
            colors: ["#eeeddd", "black"],
            category: "Sweter",
        },
        {
            id: 23,
            title: "Sweater Calado",
            price: 40.257,
            image: require("../assets/clothing/sweaterdepuntoacanalado.jpg"),
            image1: require("../assets/clothing/sweaterdepuntoacanalado1.jpg"),
            description:
                "Lorem ipsum dolor sit amet consectetur adipisicing elit.  Nobis quibusdam consectetur sunt dicta magni? Necessitatibus neque corporis?",
            size: ["S", "M", "L"],
            colors: ["#019999", "#0199"],
            category: "Sweter",
        },
    ],
};
export default api;
